export enum ResponseMessage {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_EMAIL_VERIFY_SENT = 'USER_EMAIL_VERIFY_SENT',
  USER_EMAIL_VERIFY_NOT_SENT = 'USER_EMAIL_VERIFY_NOT_SENT',
  USER_EMAIL_NOT_FOUND = 'USER_EMAIL_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_TAKEN = 'EMAIL_ALREADY_TAKEN',
  FAILED_TO_CREATE_USER = 'FAILED_TO_CREATE_USER',
  INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD',
  LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY',
}

export interface CommonResponse {
  response_message: string;
  response_data: unknown;
  extra?: string;
}
